### ISSUE TITLE
y_close

### ISSUE THREAD

**Issue by m1996** [saeedmarzban/waveCorr#3]
Hi
I've noticed that the 'y_close' is [daily returns+1] which has been shifted 2 rows. Am I right? why 2?

**Comment by saeedmarzban** [comment]
Yes, That is right. The reason is to be consistent with what happens in reality. The agent receives the close price at the end of the day, next day early in the morning puts the buy/sell request and the request is met during the day. So we consider the actual return of the stock to be during the close price at the end of next day and the close price at the end of the day after.

**Comment by m1996** [comment]
that's what I thought:)
Thank you so much

**Comment by m1996** [comment]
Sorry bothering you again, is there any especial reason for "3000" epochs?
Why not more?
